// front/src/App.tsx
import React from 'react'
import { BrowserRouter, Route, Routes } from 'react-router-dom'
import Home from './screens/Home/Home'
import Test from './screens/Test/Test'
import TestResult from './screens/TestResult/TestResult'


function App() {
  return (
    <div className="App">
      <BrowserRouter>
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/test/:testId" element={<Test />} />
          <Route path="/test/:testId/result" element={<TestResult />} />
        </Routes>
      </BrowserRouter>
    </div>
  )
}

export default App

// frontSvelte/src/App.svelte
<script>
  import { Router, Route, Link } from "svelte-navigator";
  import Navbar from './components/Navbar/Navbar.svelte';
  import Home from './screens/Home/Home.svelte';
  import Test from './screens/Test/Test.svelte';
  import TestResult from './screens/TestResult/TestResult.svelte';
  import './app.scss';

  async function getTestList() {
      const res = await fetch(`http://localhost:8080/tests`);

      if (res.ok) {
        return await res.json();
      } else {
        const text = await res.text();
        throw new Error(text);
      }
    }

    let data = getTestList();
</script>

<Router>
  <Navbar data={data} />
  <Route path="/">
    <Home data={data} />
  </Route>
  <Route path="/test/:testId" let:params>
    <Test testId={params.testId} />
  </Route>
  <Route path="/test/:testId/result" let:params>
    <TestResult />
  </Route>
</Router>
